name: build-publish-docker-image

on: 
  push:
    branches:
      - 'master'
    paths:
      - 'Docker/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACR: mcplayground
      JDK_IMAGE: mcplayground.azurecr.io/openjdk
      JDK_TAG: 17-bullseye
      CODE_SERVER_VER: 3.12.0
      REPO: mc_playground
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Trigger image build in ACR
        uses: azure/CLI@v1
        with:
          inlineScript: |
            cd Docker
            az acr build --registry ${{ env.ACR}} -t ${{ env.REPO }} --build-arg JDK_IMAGE=${{ env.JDK_IMAGE}} --build-arg JDK_TAG=${{ env.JDK_TAG }} .
