name: build-publish-function-app

on: 
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'Docker/**'
      - 'ArmTemplate/**'
      - '.github/**'
      - 'GeneratorUI/**'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_NAME: mc-playground-generator
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'GeneratorFunction'
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup DotNet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*

      - name: 'Build Project'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
